baseURL = "https://example.com/"
title = "估值PRO"
# languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

paginate = 10
theme = "binario"

[Params]
  description = "专注价值发现"
  copyright = "Guzhi.Pro" 
  columns = 2
  dateFormat = "2006年1月2日" # 日期格式
  mainMenuAlignment = "right" # 主导航右对齐
  colorTheme = "dark-green" # 绿色主题，支持dark-green, dark-blue, dark-red, dark-violet

[Params.Entry]
  # meta = ["date", "categories"] # 显示内容标签
  toc = true # 文章目录
  tocOpen = false # 默认文章目录开关
  
[Params.Breadcrumb]
  enable = true # Enable breadcrumb block globally
  homeText = "估值PRO" # Home node text

[menu]
  [[menu.footer]]
  name="标签"
  url="/tags/"
  weight="1"
  [[menu.footer]]
  name="分类"
  url="/categories/"
  weight="2"
  [[menu.footer]]
  name="归档"
  url="/achieves/"
  weight="1"